In [21]:
import numpy as np
n1=int(input("Enter no of row matrix 1:"))
m1=int(input("Enter no of col matrix 1:"))
n2=int(input("Enter no of row matrix 2:"))
m2=int(input("Enter no of col matrix 2:"))

Enter no of row matrix 1: 2
Enter no of col matrix 1: 2
Enter no of row matrix 2: 2
Enter no of col matrix 2: 2


In [32]:
print("Enter elements of Matrix 1")
A=[int(input()) for i in range(0,m1*n1)]
A=np.array(A)
A.resize(n1,m1)

Enter elements of Matrix 1


 1
 2
 3
 4


In [30]:
print("Enter elements of Matrix 2")
B=[int(input()) for i in range(0,m2*n2)]
B=np.array(B)
B.resize(n2,m2)

Enter elements of Matrix 2


 2
 3
 4
 5


In [28]:
dot = np.dot(A,B)
print(dot)

[[16 21]
 [28 37]]


In [33]:
print('Original Array:\n',A)
print('Transpose of the Array:\n',A.transpose())

Original Array:
 [[1 2]
 [3 4]]
Transpose of the Array:
 [[1 3]
 [2 4]]


In [34]:
print("Trace of the matrix:",A.trace())

Trace of the matrix: 5


In [35]:
print("Rank of the given Matrix is : ",np.linalg.matrix_rank(A))

Rank of the given Matrix is :  2


In [36]:
print("Determinant of the matrix:",np.linalg.det(A))

Determinant of the matrix: -2.0000000000000004


In [37]:
print("Inverse of the matrix:\n",np.linalg.inv(A))

Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
w, v = np.linalg.eig(A) 
print( "Eigenvalues of A:",w)
print( "Eigenvectors of A:\n",v)

Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
