In [19]:
# 1) Write a program to create an element wise comparison
import numpy as np
a=np.array([1,2,32,3,4,5,64,76,34])
b=np.array([1,2,32,8,4,5,6,7,34])
np.equal(a,b)

array([ True,  True,  True, False,  True,  True, False, False,  True])

In [4]:
np.greater(a,b)

array([False, False, False, False, False, False,  True,  True, False])

In [7]:
np.greater_equal(a,b)

array([ True,  True,  True, False,  True,  True,  True,  True,  True])

In [5]:
np.less(a,b)

array([False, False, False,  True, False, False, False, False, False])

In [8]:
np.less_equal(a,b)

array([ True,  True,  True,  True,  True,  True, False, False,  True])

In [6]:
# 2) to create a array of even integer from 30 to 70
arr=np.arange(30,70,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [9]:
# 3) to create a 3*3 identity matrix
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 4) create a vector values from 0 to 20 and change sign of numbers and range from 9 to 15

x=np.arange(21)
x[ (x>=9) & (x<=15) ] *=-1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [12]:
# 5) create a 5*5 0 matrix with diagonal elements 1 2 3 4 5 
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [13]:
# 6) to compute sum of all elemnts   
#sum of each colums and    
#sum of each row of given array 
x = np.array([[1,2,3],[4,5,6],[7,8,9]])


print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

45
[12 15 18]
[ 6 15 24]


In [29]:
# 7) to save a given array to a text file and load it
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
np.savetxt('temp.txt', x, fmt="%d") 
print("Content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [23]:
# 8) to check whether 2 arrays are equal or not (element wise)
a=np.array([1,2,32,3,4,5,6,76,34])
b=np.array([1,2,32,4,4,5,5,65,34])
np.equal(a,b)

array([ True,  True,  True, False,  True,  True, False, False,  True])

In [31]:
# 9) create 4x4 array with random values, and now create a new array from the said array swapping first and last rows.

nums = np.arange(16).reshape(4, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
nums[[0,-1]]=nums[[-1,0]]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [24]:
# 10) to multiply two given arrays of same size element by element
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))



Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]
